name: Selenium Voting Bot

on:
  push:
  workflow_dispatch:  # Allows manual execution

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install selenium
          sudo apt-get install -y chromium-chromedriver

      - name: Run script in loop
        run: |
          while true; do python pollfarm.py; sleep 5; done
